### PR TITLE
fixed logo 

### PR DESCRIPTION
**Pull request by saimohan11**
#13 
fixed logo and add some alignment and hover to login and signup

### CODE REVIEW

**Comment by saimohan11** [comment]
can you please add labels to this gsoc-extd,hacktoberfest,level-1

**Comment by saimohan11** [comment]
Add labels to this pr .then only it is valid for my gssoc.

**Comment by AKSHITHA-CHILUKA** [comment]
@anki2003ta Please add gssoc-ext and level labels to this pr .

**Comment by saimohan11** [comment]
@anki2003ta please add labels it will help me to gain some points in my leaderboard I messaged you many times in linkedin

**Pull request merged**
