### PR TITLE
Added a custom logo to the Landing page

### PR DESCRIPTION
**Pull request by swamimalode07**
image
I have added a Custom logo to the website 

Kindly  merge this request under Hactoberfest, hactoberfest-accepted , level 2 or 3 , gssoc-extd and gssoc

### CODE REVIEW

**Comment by swamimalode07** [comment]
can you add lables - hactoberfest-accepted, gssoc-extd

**Comment by swamimalode07** [comment]
can you add lables - hactoberfest-accepted, gssoc-extd please ,

**Comment by AKSHITHA-CHILUKA** [comment]
correct label is gssoc-ext

**Comment by Tejashri-Taral** [comment]
@anki2003ta please add labels to this PR

**Comment by aditya-bhaumik** [comment]
@anki2003ta Community manager this side please add all the labels to your pull requests i noticed that there are many pull requests which do not have any labels

**Pull request merged**
